"""add_user_preference_columns

Revision ID: b70ac00084ea
Revises: 
Create Date: 2026-06-18 12:53:37.730353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b70ac00084ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pref_notif_reports', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('pref_auto_process', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('pref_debug_logs', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pref_debug_logs')
    op.drop_column('users', 'pref_auto_process')
    op.drop_column('users', 'pref_notif_reports')
    # ### end Alembic commands ###
